# Generated by Django 5.0.6 on 2026-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='professional', max_length=50)),
                ('description', models.TextField()),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('features', models.TextField(help_text='List features separated by new lines')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='pricing_plans', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order', 'name'],
            },
        ),
    ]
