# Generated by Django 5.0.6 on 2026-07-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(default=5, help_text='Estimated read time in minutes'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
