# Generated by Django 5.0.6 on 2026-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_read_time_alter_blogpost_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
